### ISSUE TITLE
Style the Housing List search/filter form inputs

### ISSUE THREAD

**Issue by philhawksworth** [philhawksworth/the-united-effort-orginization#10]
This form needs to make better use of space while remaining as clear as possible.

**Comment by trevorshannon** [comment]
I saw your recent commit and it looks so good!

**Comment by trevorshannon** [comment]
Well, technically I guess I'm talking about the styling of the results, not the form.  New issue! https://github.com/philhawksworth/the-united-effort-orginization/issues/13

**Comment by philhawksworth** [comment]
Search input styling applied

**Comment by trevorshannon** [comment]
I've removed the minimum rent field (#24) and I notice that now we have three single-field fieldsets. I wonder if we can condense further?

**Comment by trevorshannon** [comment]
I spoke with a UX designer friend and she liked the headings above the single text-input fields for consistency with the headings above the checkbox groupings.  So no action needed.
