### ISSUE TITLE
Come up with Airtable editing workflow to avoid immediate live site updates

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#102]
At the moment, any edit to the Units table in Airtable will immediately be reflected in the live site.  Actually, a bit confusingly, it will be reflected in any affordable housing searches, but not in the main affordable housing database landing page (with all properties listed)

In any case, we should come up with some way to stage edits before publishing them--perhaps a duplicate table that gets directly edited before being programmatically copied over to the production table with an Airtable automation script.  

I have not explored all the options to achieve this goal yet.

**Comment by philhawksworth** [comment]
I've got some thoughts on this @trevorshannon. It's been on my mind too :)

It might be a bit audacious, but I think there might be an interesting thing we could do to both safeguard the search performance and also provide this more deliberate publishing flow.

Perhaps we I can run it past you on a call some time and if it seems viable, we could plan it out together?

**Comment by trevorshannon** [comment]
Great, I was thinking a little collaboration on this would be good.  I'll send a meeting invite and you can adjust the timing as you need.

**Comment by trevorshannon** [comment]
@philhawksworth I have some available time and no other pressing issues to work on.  Would you like me to put some time in to get this feature merged?  I'd be happy to spilt your work up into a few different pull requests so we can follow it better.

It would also be fine if you wanted to continue working on this yourself; I just wanted to offer my time since I find myself with some extra!

**Comment by trevorshannon** [comment]
@philhawksworth made a fantastic version of the website in #139 that includes data caching and edge functions to enable much faster live filtering.

I am beginning to commit some changes that follow the lead of #139.  I will first focus on keeping Airtable updates out of our live site via caching, then move serverless functionality to edge, and then some other miscellaneous improvements/refactors made in #139

**Comment by trevorshannon** [comment]
All airtable data fetching now happens at build time.  For serverless pages, the cache is simply indefinite, so it re-uses data fetched at build time when doing a serverless render on request.

There are some other improvements in #139 that I've made into separate issues, e.g. #191, #193
