### ISSUE TITLE
No favicon on property details pages

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#103]
There seems to be no favicon loading on individual property pages (rendered from the units.js serverless function).

https://www.theunitedeffort.org/housing/affordable-housing/1367

This could be because unit.js uses a "shadow" base template that is not the same as the rest of the website.  There is an open issue to consolidate the templates already.

**Comment by philhawksworth** [comment]
Doh! Good catch. That will only take a moment to fix. I'll mop it up. :)

This is a good example of why we should extend the use of Eleventy Serverless through to the units view as you mentioned, @trevorshannon.
