### ISSUE TITLE
Update Housing Database schema

### ISSUE THREAD

**Issue by philhawksworth** [philhawksworth/the-united-effort-orginization#11]
Time to make some changes to the field names and data types in the Airtable DB.
And also ensure that the new field names are used wherever they are referenced in the code to pull in data

**Comment by trevorshannon** [comment]
Airtable schema has been updated.

Interim fields 
TEST_RENT_PER_MONTH_USD, TEST_MIN_INCOME_PER_YEAR_USD, TEST_MAX_INCOME_PER_YEAR_USD
are still present, but now copies have been made called
RENT_PER_MONTH_USD, MIN_INCOME_PER_YEAR_USD, MAX_INCOME_PER_YEAR_USD
All of the above are numerical fields.

I will soon make the associated code change to use the new field names (without TEST_) and then will mark the original fields RENTS, min_income, and max_income as deprecated.
