### ISSUE TITLE
Add more information about donations to 'Donate' section

### ISSUE THREAD

**Issue by clairehubel** [philhawksworth/the-united-effort-orginization#129]
I would like to add the following info to this section: 

1. EIN #
2. PayPal button for donations
3. Amazon smile button for donation

@trevorshannon Would you like me to break these down into separate issues so they can be added as I get the info needed, or address them all at once?

**Comment by trevorshannon** [comment]
If all 3 items are set up and ready to go, we can keep them all as a single issue.  Otherwise, I'm happy to add the items one at a time as they are ready.

**Comment by clairehubel** [comment]
OK.....I am dependent on getting banking info from Julie, but I will make a start on it and let you know as stuff comes in. Thanks :)
