### ISSUE TITLE
De-dupe items in the affordable housing results list

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#13]
Provide an easy-to-read summary of property listings showing such info as unit types (Studio, 1 Bedroom) and availablility/status instead of a basic unordered list of property names.

**Comment by trevorshannon** [comment]
New styling looks amazing.  @philhawksworth you are probably on this already, but if not let me know.  I bet we can group rental properties by name and show multiple unit type badges if there are more than one.  See attached picture.

<img width="544" alt="Screen Shot 2022-04-30 at 2 35 32 PM" src="https://user-images.githubusercontent.com/4656936/166123603-fc0b56d5-b2a8-4b09-a940-a868e41914ee.png">

**Comment by philhawksworth** [comment]
Oh good catch, @trevorshannon! 

Yes we should totally do this! We also have an issue describing what information to show for each address in this results lists in a related issue. I'm going to keep both issues open, but lets use #2 as where we track what data to show, and keep this issue purely to track the de-duping of items in the list. 

I'll update the issue title to reflect that.

**Comment by trevorshannon** [comment]
@philhawksworth have you started on this, or can I re-assign to me?

**Comment by trevorshannon** [comment]
You know, I think this is the best issue for me to work on at the moment, so I'll risk duplicating effort and go ahead and do this one now. I hope I don't cause a problem 😬

**Comment by trevorshannon** [comment]
Ok, this has been fixed.  Still hoping you did not have any WIP @philhawksworth! 🤞

**Comment by trevorshannon** [comment]
Re-opening as my implementation does not work well for properties that have different statuses for different unit types.  At the moment, if a place (let's call it The Great Property) has the waitlist open on 1BR and the waitlist closed on 2BR, then the filter results will show something effectively like this:

The Great Property
Waitlist Open 1 bedroom
1234 Main St, San Jose

The Great Property
Waitlist Closed 2 bedroom
1234 Main St, San Jose


So still some duplication.   Maybe the chips could be combined better when the statuses are different.

Not sure if this needs to be done by the relaunch.
