### ISSUE TITLE
Improve the Housing db Update Process for June Updates

### ISSUE THREAD

**Issue by clairehubel** [philhawksworth/the-united-effort-orginization#132]
I would like to propose that we now streamline our housing db update process, having participated in this last month and seen how it can be improved.

@trevorshannon How close are you to designing a page that can be used by volunteers for this process? Your description of a page that could list property info with a view to updating this form to capture changes was great. DB updates would be a piece of cake if this were the system. Currently volunteers who are not simultaneously updating the db when searching for changes will make non-specific remarks that require digging on the part of the person making updates in the db, thereby duplicating efforts and making the process take much longer than it should.

I propose:
1. For properties included in Bruce's auto-screening we only search property websites in which a change is noted. He is adding properties to this list on a daily basis, and I think could be responsive to some gentle deadlines each month.
2. Volunteers search for the changes and mark them on the form you are describing
3. Someone enters info into db. I can easily do this now, esp as the number of entries will be fewer, and the specific changes will be listed.4. 

Poul Erik commented that he prefers to search for changes and make these edits to the DB himself, which would be a great way to cover the properties not covered by Bruce's auto-screening.

I can recruit additional volunteers to help  with this, since we should easily be able to spread this work out over many people, and the work would be easier to follow. We have tried recruiting people for this task in the past, but they have fallen by the wayside bc the process is overly complicated and not intuitive.

If you think having this form is an option by the middle of the month it would work well for the timeline, since we will want to start the updates in the last week of June.

**Comment by trevorshannon** [comment]
Yes, I will aim for having something in place by the middle of this month.  Overall, it's been a bit more of a project than I initially anticipated, but I'm now in a good spot to sign up for a deadline like that.  I would love to be able to give it a trial run for the June update (roundabout 6/23 or so, I believe)

**Comment by clairehubel** [comment]
That would be terrific. Even without it, I think we will be in better shape given Bruce's contribution. How is the workload in general? We have burned people out in the past, so I want to make very sure that doesn't happen to you. Please give me feedback as needed!

**Comment by trevorshannon** [comment]
I think we will be trying this process out for the next cycle, so marking as complete.
