### ISSUE TITLE
Define SRO next to filter label

### ISSUE THREAD

**Issue by clairehubel** [philhawksworth/the-united-effort-orginization#133]
@trevorshannon 

I sent the link db link to someone today and they asked me what SRO meant. To make this as clear as possible, could we please add this definition right at the filter? So it would say:

SRO (Single Room Occupancy)

under Type of Unit, here: https://www.theunitedeffort.org/housing/affordable-housing/

**Comment by trevorshannon** [comment]
There is a definition that pops up when you hover (and linger) over "SRO" per #55 but I guess it is not discoverable enough.  I'll copy this comment into #55 and we can improve the solution.
