### ISSUE TITLE
Printable tracking log view

### ISSUE THREAD

**Issue by philhawksworth** [philhawksworth/the-united-effort-orginization#145]
A tracking log is a view of the search results presented in a grid along with useful headings which help the user negotiate their application process.

It is similar to the the optimised print view, but includes more structure.

It should:

- Accessed via a button labelled: "Show my results in a tracking log"
- Be presented on a new page including a print button
- Be comprised of:
  - Property (concatenation of the following)
    - Name
    - Address 
    - City
    - Phone
    - Email
  - Application completed
  - Submission details (description: Date submitted, Submissions method, Received by, etc)
  - Follow up 1 (1 month after submission, Confirm your current contact details, Verify that you are on the waitlist)
  - Follow up 2 (6 months after submission, Confirm your current contact details, Verify that you are on the waitlist)

**Comment by trevorshannon** [comment]
Initial tracker view can be seen [here](https://feat-tracking-log--ueo.netlify.app/housing/affordable-housing/tracker?availability=Waitlist+Open&city=Cupertino&includeUnknownIncome=on&includeUnknownRent=on&income=&propertyName=&rentMax=)
