### ISSUE TITLE
Use existing common base template for rental property pages

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#15]
The page shown for a single rental property uses a copy of the "true" website base template and should instead use the same template file so as to keep it in sync with the rest of the website.

**Comment by trevorshannon** [comment]
@philhawksworth any reason these apartment units pages can't all be pre-rendered?

**Comment by philhawksworth** [comment]
They _could_ all be pre-rendered, @trevorshannon. But with so many of them (and the number hopefully, growing) this will make for an increasingly long build. For the sake of the authoring/publishing experience, and the amount of build minutes used, I recommend we try to keep these out of the site generation. 

What we can do instead is render them on demand the first time they are requested, and then cache them for future requests. This would use something call Distributed Persistent Rendering (DPR). And I can help with that :)

I suggest we add that as an enhancement issue which is not a blocker to the 2.0 launch milestone, and then add it to the backlog to prioritise along with the other items in the next iteration.

**Comment by philhawksworth** [comment]
While this is important, I'd argue that it should not block us from relaunching, so I've removed it from the milestone and added to the next one.

**Comment by trevorshannon** [comment]
True true.  Luckily it should be an easy fix.

**Comment by trevorshannon** [comment]
This issue may be made obsolete by some work @philhawksworth is doing with regards to tightening up the database edit workflow #102, so we can revisit after that's settled.

**Comment by trevorshannon** [comment]
The apartment details pages are now all rendered at build time (@philhawksworth and I agree that they render quite fast), so they use the existing `base.liquid` template instead of a shadow `base.js` template.

We can revisit on demand rendering with netlify's DPR later on.
