### ISSUE TITLE
Add "all" to number of results string in affordable housing table view

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#157]
When no query parameters are present, we should add the word "all" to "Showing N properties" on the [table summary view](https://www.theunitedeffort.org/housing/affordable-housing/table?).

This would make the behavior the same as the [list view](https://www.theunitedeffort.org/housing/affordable-housing/)

When filters are applied via the URL query parameters, those filters will be shown above the table, and the "all" should be removed from the "Showing all N properties" text.  Again, consistent with the list view.

**Comment by rajivrajiv** [comment]
Can  you assign this to me?

**Comment by trevorshannon** [comment]
@rajivrajiv great, I was able to assign after your comment.  Thanks!
