### ISSUE TITLE
Make phone number on property details page a link

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#172]
In the [affordable housing search results](https://www.theunitedeffort.org/housing/affordable-housing/filter?rentMax=&includeUnknownRent=on&income=&includeUnknownIncome=on&propertyName=Alma+Family#results), the phone number for a given property is a `tel` link.  In the [property details page](https://www.theunitedeffort.org/housing/affordable-housing/902), it is not.  It would be better for the number to be a link so that folks can click on it to call.

**Comment by Mannuel25** [comment]
Hello @trevorshannon , I'd love to work on this, could you please point to me the file to fix it.

**Comment by trevorshannon** [comment]
@Mannuel25 fantastic!  Thanks for offering to help.  You can find the relevant file [here](https://github.com/philhawksworth/the-united-effort-orginization/blob/main/netlify/functions/units.js).

The README for this repo is a bit out of date, so if you are interested in setting up a dev environment, I can lend a hand.  Otherwise, I'll just test your changes in my dev environment prior to approving a pull request.

**Comment by trevorshannon** [comment]
Ah, no problem.  The only purpose of that JS file is to generate an HTML string which then gets shown by the browser.  You would add something very similar to [this line](https://github.com/philhawksworth/the-united-effort-orginization/blob/main/netlify/functions/units.js#L98), except you'd check for the phone key instead of email.  The keys themselves are defined [lower down](https://github.com/philhawksworth/the-united-effort-orginization/blob/main/netlify/functions/units.js#L351) in that file.

If you want to play around with Javascript, there are many resources online, and you can always open the developer tools in Chrome to use the javascript console.  There, you can type in any javascript and execute it to see what it does.

If you'd rather not work on this issue, that's not a problem.  You can unassign yourself or ask me to if you lack the permissions.  But it would also be a good way to learn!

**Comment by trevorshannon** [comment]
@Mannuel25 actually, some other unrelated refactoring has just led to this no longer being an issue.  If you would like to contribute on a different issue in the future, please do comment it!  Thanks very much for offering to lend a hand.
