### ISSUE TITLE
Ingest latest data from legacy database one last time

### ISSUE THREAD

**Issue by philhawksworth** [philhawksworth/the-united-effort-orginization#20]
Before we cutover to our new site, we need to do one final capture of the legacy database to ensure that we have included every last update.

This will involve:

- [x] Crawling the housing listing page JS fetch
- [x] Creating proxied pages to circumvent legacy site session failures
- [x] Crawling the original site housing pages via proxied pages
- [x] Uploading CSVs to Airtable (suggest temporary new Housing DB and Units tables in the base)
- [x] Updating schema of new imported tables to match our production schema
- [x] Deprecating existing Housing DB and Unit tables and updating the table IDs in our website
- [x] Informing everyone that they should no longer update the legacy DB!

**Comment by philhawksworth** [comment]
@trevorshannon This process has begun. You can see the progress in the checklist above.

Since there has been some work on the schema of the `Housing Database` and `Units` tables in Airtable, I opted to import the final data into 2 new tables which each have the same fields as the existing tables.

Please find `[IMPORT] Housing Database` and `[IMPORT] Units`

These are linked via a relationship of the ID fields, just as the existing table are. Since you had massaged some of the data and added things like coords data, I'd like to hand this over to you at this stage. 

Make sense?

**Comment by trevorshannon** [comment]
Perfect, I'll take it from here!  Thank you very much.

**Comment by trevorshannon** [comment]
@philhawksworth I have noticed some problems with the latest data import.

It seems like the AMI percentage values were imported into the `deprecated_RENTS` field, so I am not able to generate values for the numerical field `RENT_PER_MONTH_USD`

Likewise, I think:
the `min_income_details` field data was copied into the `deprecated_min_income` field 
the `max_income_details` field data was copied into the `deprecated_max_income` field

Hopefully this is easy to fix!  I know the data import is a pain...

**Comment by philhawksworth** [comment]
Thanks for exploring and validating this, Trevor! T

he import is of a CSV file (generated with various web scraping gymnastics) so it's not very sophisticated. But I'll explore and get things into the right shape.

**Comment by trevorshannon** [comment]
Ok, thanks!

Also adding a mention of #31 here just to sort of link the two issues together

**Comment by philhawksworth** [comment]
Once we have the data in the right fields, are we safe to remove those deprecated fields, @trevorshannon? If so, I'll do so as part of this work.

**Comment by trevorshannon** [comment]
Yes, but I'll track that in the separate issues having to do with each of
the fields.  For now just populating those deprecated fields as they were
means I can do my tweaking prior to deleting the deprecated fields.

**Comment by clairehubel** [comment]
Thank you! you guys are the ones keeping me going with all this!

**Comment by philhawksworth** [comment]
Data reimported to the `[IMPORT] Housing Database` and `[IMPORT] Units`, @trevorshannon 

The scheme looks correct to me now. Although those tables don't have content that appears to have been manually input since it wasn't part of the import previously.

**Comment by trevorshannon** [comment]
Great!  Yes, at first glance it looks to be correct now.  Thank you very much.

I will get started today on the manual data input you mentioned as well as some other pending db cleanup.

**Comment by trevorshannon** [comment]
Ok, I have just pushed a change to main that switches to using the newly imported data instead of the older data.  I've kept the old data tables in Airtable for now, but moved them to the end of the list and prepended them with [DEPRECATED].  I've also deprecated some fields, but I will leave them in place for now until all seems OK.

@philhawksworth can you make the CSV source files you generated available somehow?  I'd like to have a backup copy just in case.

**Comment by philhawksworth** [comment]
Outstanding!
Adding the CSV sources here for posterity. 

[housing-export.csv](https://github.com/philhawksworth/the-united-effort-orginization/files/8693606/housing-export.csv)
[units-export.csv](https://github.com/philhawksworth/the-united-effort-orginization/files/8693607/units-export.csv)
