### ISSUE TITLE
Cache housing detail pages after first on-demand render

### ISSUE THREAD

**Issue by philhawksworth** [philhawksworth/the-united-effort-orginization#21]
Use [Distributed Persistent Rendering](https://www.netlify.com/blog/2021/04/14/distributed-persistent-rendering-a-new-jamstack-approach-for-faster-builds/) to cache the housing detail pages after they are first rendered on-demand via a request to their URL.

This will help to improve performance without incurring a cost to the speed if the deployments.

As discussed in #15

**Comment by trevorshannon** [comment]
Ultimately decided to generate all of these pages at build time.  ref #15 #102
