### ISSUE TITLE
Add eligibility tool form fields

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#213]
As part of our effort to implement a program/benefit eligibility tool (#98), the current form skeleton needs to be populated with the form fields mocked-up in [this document](https://docs.google.com/presentation/d/1GZGhu7K2GtutdVy3EugUAZfc80Clt7id7b8CJo7YMBg/edit?usp=sharing). 

This issue is specifically aimed at adding those fields; nothing needs to be done yet with the data from the fields.  Once the fields and form pages are all set up, we can begin implementing logic to determine eligibility from the form field data.

**Comment by trevorshannon** [comment]
@rajivrajiv if you could please add a comment to this issue, I will then be able to add you as an assignee.

**Comment by rajivrajiv** [comment]
Could you please assign this?
Thank you!

**Comment by trevorshannon** [comment]
@rajivrajiv I think this is complete, is that right?  If you know of any additional form fields that need to be added let me know.  Otherwise, you are free to close the issue.

**Comment by rajivrajiv** [comment]
I used unassign me, to close out.

**Comment by trevorshannon** [comment]
Ah, did you not have the appropriate permissions to close the issue?  No problem, I'll take care of it.

**Comment by rajivrajiv** [comment]
I did not find an option to close the issue. I could be a permissions problem.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
