### ISSUE TITLE
Add message warning users about the possibility of out-of-date information

### ISSUE THREAD

**Issue by clairehubel** [philhawksworth/the-united-effort-orginization#36]
There is a chance that we generate a list of $ amounts, calculated with reference to the 2022 AMI, but the apartment's website may still be using the 2021 AMI. To acknowledge this (and other) possible discrepancies, would it be a good idea to have some kind of disclaimer, eg "Exact prices to be confirmed by the property" or something along these lines?

**Comment by trevorshannon** [comment]
Agree. Generally, our database may be out of date at any time, so having a disclaimer like that regardless of whether we're calculating values ourselves is prudent.

**Comment by trevorshannon** [comment]
Added the following at the bottom of the housing results list: "We strive to be as accurate as possible, but always confirm property details with the property manager." 

in commit bc24e592
