### ISSUE TITLE
SRO and Studio should be listed before 1 Bedroom, etc

### ISSUE THREAD

**Issue by clairehubel** [philhawksworth/the-united-effort-orginization#38]
@trevorshannon Please list SRO, then Studio, ahead of 1 bedroom, etc. It's not alphabetical, but it makes more sense from the point of view of apartment-type.

**Comment by trevorshannon** [comment]
In that case, we should also use that same ordering for the Studio, 1 Bedroom, etc info chips in the list of results and for the ordering of the rent tables in the individual property pages.
