### ISSUE TITLE
Add minimum occupancy data field

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#42]
Many places have a minimum occupancy for a given unit type (e.g. a single person can't rent a 3 bedroom place) but that data is not in the Airtable (and I think, not even in the current UEO database)

**Comment by clairehubel** [comment]
Good idea. It's interesting to see how much this database can be improved upon and refined as we continue to work on it. This attention to detail is going to make it a really valuable resource for the folks using it.

**Comment by trevorshannon** [comment]
I've confirmed the minimum occupancy data is not in our legacy database either.

I've added the field to Airtable, but it is not populated with data yet.  I'll leave this open until the data is added.

**Comment by trevorshannon** [comment]
This data should slowly get populated as properties are checked for changes.
