### ISSUE TITLE
Ensure all SRO maximum occupancy is 1 in Airtable

### ISSUE THREAD

**Issue by clairehubel** [philhawksworth/the-united-effort-orginization#47]
@trevorshannon SRO stands for Single Room Occupancy (you may well know this!)......so in any case where SRO is mentioned, the maximum occupancy will alway be 1. I noticed that in some cases, it says 'call for info'

Could you please check that in all cases, the maximum occupancy for the SRO's is 1?

**Comment by trevorshannon** [comment]
Can do. I'll add this to the list of database clean up tasks that need to
be done after our final data ingestion from the current db.

Separately, I had actually been considering defining SRO on the website
somehow. Do people know what that means generally?

**Comment by clairehubel** [comment]
Good idea to include the definition of SRO somewhere. It's an important term to know when searching for affordable housing, and I'm not sure everyone using the site will know the meaning.

**Comment by trevorshannon** [comment]
Ok, I made issue #55 for that.

**Comment by trevorshannon** [comment]
Done in the newly imported temporary table which is pending promotion to production.
