### ISSUE TITLE
Make rent tables more clear and easy to understand

### ISSUE THREAD

**Issue by clairehubel** [philhawksworth/the-united-effort-orginization#49]
@trevorshannon 

https://ueo.netlify.app/housing/affordable-housing/854

For the page above, I am not clear on why there are 4 values listed for each type of apartment. I am assuming that the first value pertains to SRO, the second pertains to 1BR, the third to 2BR.....how about the fourth value? 

This may well be a result of the way the original db was constructed. Is there a way to clarify this? Ideally, only the relevant value for the SRO result would be the one that is shown in that section, etc

Once this is clarified, the change should be applied to all pages where this is an issue.

**Comment by trevorshannon** [comment]
I agree that this is confusing.  For a [property with more information](https://ueo.netlify.app/housing/affordable-housing/901), it's a bit more clear (but still confusing).

Each row is associated with a different income level (also represented sometimes as a % of AMI).  Looking at the property management page for listing 854, it seems that there are 4 income brackets they use (15%, 20%, 35%, 45% AMI).  Rent is not listed on their page, so the table (which is really meant to show our visitors rent) ends up being just confusing.  We'll definitely have to think about the best way to show this info, and I bet some database cleanup will be needed as well to get what we want.

**Comment by philhawksworth** [comment]
Reviewed with @clairehubel. The tooltips and added details seems to do the trick. 
Yay @trevorshannon !

**Comment by trevorshannon** [comment]
Great.  I think that perhaps a column showing something like "income bracket 1" or "40% AMI bracket" could add clarity to the different rows.  #66 will help too.

**Comment by trevorshannon** [comment]
Reopening because there are some properties that still have unclear rent tables.  Here is an example (property 960).  It's not clear at all why there are two rows per unit type.  There are two units because the property manager's website says they offer apartments to the 50% AMI and 60% AMI brackets, but have no further details.  This results in two records in our db: one for 50% AMI and one for 60% AMI.  However, since we don't show that information, the table we display is confusing.

<img width="400" alt="Screen Shot 2022-05-19 at 2 02 23 PM" src="https://user-images.githubusercontent.com/4656936/169404217-95dd9829-41f1-4447-8340-d113a67c93eb.png">

**Comment by trevorshannon** [comment]
I have a feature branch that adds AMI information to the table.  This information is not always available, so the trick is deciding what we want to display in that case.  Here are some examples:

The same table that was confusing previously (property 960):
<img width="600" alt="Screen Shot 2022-05-19 at 2 09 48 PM" src="https://user-images.githubusercontent.com/4656936/169405362-1c3feea0-820a-411c-918b-bf9f030a689d.png">


A property with no AMI information (property 1091):
<img width="600" alt="Screen Shot 2022-05-19 at 2 01 08 PM" src="https://user-images.githubusercontent.com/4656936/169405903-3f1115b7-d42b-46dd-804d-f9b982bfe545.png">


Another property with no AMI information but with rent information (property 890):
<img width="600" alt="Screen Shot 2022-05-19 at 2 16 56 PM" src="https://user-images.githubusercontent.com/4656936/169406124-0cedc547-59f4-4df6-9830-63e4215c75b3.png">

**Comment by trevorshannon** [comment]
Committed to the develop branch. We can always make changes later.
