### ISSUE TITLE
Speed up housing results filtering

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#50]
It currently takes ~ 5-8 seconds to load the results of an affordable housing filter.  We can do better.

**Comment by philhawksworth** [comment]
there's a bunch of optimisations we can do, and we can also cache the results via DPR which will make repeated searches close to instant

**Comment by clairehubel** [comment]
I noticed that too. I wasn't sure why it was, but happy to hear there's a way to improve this :)

**Comment by trevorshannon** [comment]
Some low-hanging fruit was to cache the filter options generated at build time so that subsequent affordable housing page loads can use that cached JSON object instead of recreating it each time with a call to Airtable.  When applying filters, the page loads about twice as fast now.  I'll close for now because the loading time seems reasonable, but if anyone disagrees please re-open.  We can also make separate issues for other optimizations, caching filter results, etc.

**Comment by trevorshannon** [comment]
well, #58 introduced a bug (#59) so I'm reopening this.

**Comment by trevorshannon** [comment]
the bug (#59) has been fixed in #67

We can re-open or make a new issue if we want to do further optimizations in the future.
