### ISSUE TITLE
Avoid contextual/hover UI for accessibility and mobile compatibility reasons

### ISSUE THREAD

**Issue by philhawksworth** [philhawksworth/the-united-effort-orginization#53]
I recommend that wherever possible, we avoid introducing contextual tool-tips and information that reveals itself on hover.

Recently we've moved some descriptive text into a tooltip on the housing form. While this does remove some text form the page and reduces some noise, it also introduces a new UI device and also demands an "intent to discover" from the user rather than presenting that information right there on the page.

<img width="408" alt="Screenshot 2022-05-06 at 14 46 55" src="https://user-images.githubusercontent.com/5865/167145669-c61dc77f-503e-4d73-93d7-ff14b89b7379.png">

Revealing content on hover is also problematic on mobile, non-mouse-based devices and is generally best avoided if possible.

I'd suggest that instead we establish a consistently used inline text style for additional contextual information.

**Comment by trevorshannon** [comment]
Yes, I struggled with this for the reasons you mentioned.  Ultimately, I decided that in a few choice locations something like this is a good balance between conciseness and keeping the pages dead simple.  The main driver for adding the tooltip icon at the Yearly Income location and in the rent tables was viewing on mobile.  With too much text, it gets difficult to keep the pages reasonable on mobile.  But generally I agree that the simpler and less interactive the page, the better.  In this particular case, the info hidden behind the icon is not critical, and a user who does not discover it can still use the website effectively.

Before doing this I did test on my phone (Pixel 3) and the hover behavior was great: tap the icon to see the help text, tap elsewhere to hide it again.  Admittedly, this may not be the behavior on all mobile devices.  @philhawksworth, do you know if that's the case?

**Comment by philhawksworth** [comment]
Thanks for being so thoughtful and conscientious about this @trevorshannon. It's such a tricky area when we're trying to have good confidence that all users will get a good experience on all devices. There are so many, and most of our users are unlikely to have the snazzier, more capable ones.

Perhaps we can chat about it and talk through a few options. It's not a blocker, but the more UI details and conventions we add the more careful we need to be. So it's worth us sweating the small stuff now to help us down the road.

**Comment by trevorshannon** [comment]
Yes agree about sweating the small stuff!  Thanks for bringing it up.  I'm happy to talk separately on this to see what would be best.  Just email me separately and I'm sure we can find a good time to call again.  Would be good to touch base again anyways.

**Comment by trevorshannon** [comment]
I believe this has been resolved with #153
