### ISSUE TITLE
Avoid third-party javascript in the rendering path

### ISSUE THREAD

**Issue by philhawksworth** [philhawksworth/the-united-effort-orginization#54]
We recently added Font Awesome as a means of using some fonts.

I'd recommend avoiding this if possible. By requiring a third party Javascript asset in our critical render path we are adding some performance bottlenecks and failure points into our site which we can avoid. The site will be faster and more resilient without it.

Instead we should use a carefully chose variable font (done) which is subsetted (todo) for greater performance. I think we can avoid any third party dependency for typography.

**Comment by trevorshannon** [comment]
oooh, I just learned about the <path> tag.  interesting.

**Comment by philhawksworth** [comment]
I certainly don't want to swoop in and undermine any efforts. But I can help with this a little since it's an area I focus on for work. :)

**Comment by trevorshannon** [comment]
Lol I just realized the tag text in [my comment](https://github.com/philhawksworth/the-united-effort-orginization/issues/54#issuecomment-1119732959) got totally clobbered by the markdown.  I _meant_ to say "I just learned about the `<path>` tag."

Yes @philhawksworth go for it!

**Comment by philhawksworth** [comment]
Closed by #96
