### ISSUE TITLE
Define SRO or use "Single Room Occupancy" string instead

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#55]
"SRO" is a unit type but it would probably be better to write out the acronym "Single Room Occupancy" instead.

**Comment by philhawksworth** [comment]
This could be done with a a footnote or `abbr` tag to add the info

**Comment by philhawksworth** [comment]
We now have this abbreviation defined in the make using the `abbr` tag to provide screen reader support.
Touch devices show the abbreviation inline on focus.
Mouse devices show with standard browser UI on hover.

**Comment by trevorshannon** [comment]
This is very minor, but the standard browser behavior for me (Chrome, Mac) makes the definition of the abbreviation a bit hard to find on this particular mouse device.  I think this is partially because the default hover timeout before the tooltip appears is a bit long, but also because the abbreviated text is also an input label.  As expected, if I click on the SRO label, the corresponding checkbox toggles.  However, by clicking on the text it seems that prevents any future tooltip from appearing.  So if I click on SRO and leave my mouse there, no abbreviation definition appears.  If I move my mouse away and then back over SRO, the definition eventually appears. 

re-opening so we can keep track of this, but removing it from the 2.0 launch milestone.

**Comment by trevorshannon** [comment]
from @clairehubel, moving from #133 

"I sent the link db link to someone today and they asked me what SRO meant. To make this as clear as possible, could we please add this definition right at the filter? So it would say:

SRO (Single Room Occupancy)"

**Comment by clairehubel** [comment]
I see the hover feature. I like it, but I think it has to pop up more quickly for people to notice it. Also, on the mobile version, the definition seems to pop up only when the filter is selected, which I think should be changed. Minor detail, I know, but if this can be improved then it would be good, bc many of our clients will be interested in SRO properties.
