### ISSUE TITLE
Add an easy way to add and edit affordable housing data

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#56]
We have a fairly large number of fields associated with each affordable housing property.  With multiple unit types and multiple income brackets for each unit type, updating details for a property can be daunting. 

We could probably make things easier by presenting a well-formatted and pre-populated form allowing UEO volunteers to edit the exact field they care about.

A similar form (not pre-populated) could be used to add a new entry with full rent/income information.  I suspect we will not want to lean on community members to put in the rent/income details, so that data entry form is in a different issue, #22

**Comment by clairehubel** [comment]
#56 

I liked this idea initially, but is there a reason that the info cannot be changed directly on the airtable? Are you concerned about info on there getting messed up?  It seems as though it would be fewer steps to do it this way, and preferable from that standpoint?

**Comment by trevorshannon** [comment]
The info _can_ be directly changed on the Airtable.  However, there are a few reasons this may not be a good idea:

1. It is not always easy to tell from the Airtable grid view which exact field needs to be modified to update, say, the min income for the 40% AMI bracket of a given apartment.  It certainly can be done but seems a bit error-prone
2. There are some special linked fields connecting the "Housing Database" table with the "Units" table and accidentally editing one of those fields could cause problems on the website.
3. Some fields may need to be calculated, and having a calculation within the Airtable itself is not always the best option.  While certainly not the only way to achieve this, having a separate form for data entry allows us to run some code and do some calculations prior to entering or updating a record.  An example would be re-generating the GPS coordinates of an apartment if somebody corrects the address field.

I think the number of steps for the person updating would ultimately be the same, it's just whether they do the update steps in the Airtable interface or in a custom interface we provide.

For starters though, we will absolutely be doing updates in Airtable simply because it takes time and work to make that fancy custom update interface :)

**Comment by clairehubel** [comment]
This all makes perfect sense, and I agree. I guess initially post-launch, you will be the one doing the updates (although Wei/Poul Erik could help identify the changes perhaps?), and then once you have figured out how to generate the form, then it can be outsourced? I hope you don't plan on going anywhere anytime soon! 😊

**Comment by trevorshannon** [comment]
Yes I can do initial updates, but I should pretty quickly train up a few
other folks so we have some redundancy.  My hope is that with a better data
input form the training required for a new person will be minimized.

**Comment by trevorshannon** [comment]
The bulk of the work for this updates tool is complete.  I will begin working on documentation so others know how to use it.  There is also a bit of work to do around sending the automated email with a summary of the changes input by our volunteers.  I expect this all to be wrapped up by the time we begin our update this month.

I will send a wider email announcing this, but you can take a look at the tool here: https://develop--ueo.netlify.app/contrib/affordable-housing/campaigns/example-amgKikwkGEavdA

The above link is just an example to show how the tool works.  No database changes will be made or anything, so feel free to play around and look for issues!

I imagine a small group of us will use the tool this month, and then perhaps we can expand our set of volunteers for the update after this one. Once I fix all the bugs we inevitably find ;)

**Comment by trevorshannon** [comment]
email generation script has been finished up, closing this issue.
