### ISSUE TITLE
Create "View housing list as checklist" view for easy printing

### ISSUE THREAD

**Issue by philhawksworth** [philhawksworth/the-united-effort-orginization#6]
The housing list search results page should include a link to "View this list as a printable checklist" which:

1. takes you to the same results on a new page with some different formatting
2. shows the results in a grid
3. Includes suitable  summary/metadata about each item
4. adds columns for the user to write in for tracking their progress and making notes once printed
5. adds a clear "Print this list" button

**Comment by trevorshannon** [comment]
This is being tracked in #145 instead.
