### ISSUE TITLE
Recategorize all Suite database entries

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#63]
From Wei:
"Suite". Only two properties for DV survivors have suites.

**Comment by trevorshannon** [comment]
request from weiqune is to keep the data in Airtable but change the housing type to one of the more commonly-used options.

**Comment by philhawksworth** [comment]
Do we have insight into which type would be more appropriate?
Perhaps something for you and I to discuss and action when we chat on Saturday, @clairehubel.

Also, we know have a  `Content update` label here in GitHub issues for things which are just a content change

**Comment by trevorshannon** [comment]
The two properties have been recategorized as SRO after email discussion
