### ISSUE TITLE
Recategorize all Hotel Room entries from database

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#64]
from Wei:
"Hotel Rooms". Only Hotel California has hotel rooms.

**Comment by trevorshannon** [comment]
request from weiqune is to keep the data in Airtable but change the housing type to one of the more commonly-used options.

**Comment by philhawksworth** [comment]
Reclassified this one as a Studio.

**Comment by trevorshannon** [comment]
My understanding of SRO is that it's nearly exactly the same as a hotel room, so I thought this was going to become SRO.  That said, I don't know a lot about SROs so maybe @clairehubel can chime in.

**Comment by trevorshannon** [comment]
Ah, I see that on https://altahousing.org/properties/hotel-california/ there is an option for two people in one unit, so maybe Studio is correct. This raises the following questions in my mind @clairehubel:

How is SRO different from Studio?
Are SROs truly always 1 person only?
