### ISSUE TITLE
Synchronize housing search options on housing db landing page and search page

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#7]
When executing a housing search, the page template for the search results is different than the page template for the affordable housing landing page (from which the search is initiated).  These templates should be the same.

At the moment the affordable housing landing page builds the search/filter options with a js-backed liquid template.  That same liquid template can only be used at build time, not on-demand. 11ty-serverless may provide a way to use the same liquid template for the page rendered at build time and the (very similar) search results page rendered on demand.

**Comment by trevorshannon** [comment]
Still a ways to go and some cleanup to do, but I just committed a working prototype on the 11ty-serverless branch.  It uses the same .liquid template for the static affordable housing landing page and for the subsequent filtering a user may apply. https://feat-11ty-serverless--theunitedeffortorginazation.netlify.app/housing/affordable-housing/

One thing I am trying to think through is how to _always_ statically generate a portion of the page (the set of available filter checkboxes) while dynamically generating the filter results (list of rental properties).  Currently, the list of filter options is regenerated by hitting the Airtable API every time a user applies a new filter.  There must be some way to save an HTML snippet somewhere at build time and inject that into the page rendered by eleventy serverless.  I have not looked too much into it yet, but if you know of some way offhand @philhawksworth then let me know!

**Comment by philhawksworth** [comment]
@trevorshannon Are you happy for me to contribute a little on this feature branch? I'd like to add some further styling to your form.

(I'm keen to contribute and assist, but would hate to step on your toes)

**Comment by trevorshannon** [comment]
@philhawksworth in case you need a mention to get an email?  I'm new to Github Issues.
