### ISSUE TITLE
Update content of CalFresh page

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#72]
https://ueo.netlify.app/public-assistance/calfresh/

New content is in this document:  https://docs.google.com/document/d/1rDr-np-Wy1XZv-xM398wrtSAeV1b00wM/edit?usp=sharing&ouid=104655587815561246261&rtpof=true&sd=true

**Comment by clairehubel** [comment]
@philhawksworth do you have time to take this one? It's just a case of formatting it to match. I could likely figure it out but not before the launch this weekend.

**Comment by philhawksworth** [comment]
Absolutely. That's a simple one for me, given my familiarity. Give it me!

**Comment by clairehubel** [comment]
Thanks Phil! :)

**Comment by philhawksworth** [comment]
This is done and will get published along with the next deploy.
(available already in the preview: https://preview-ueo.netlify.app/public-assistance/calfresh/)
