### ISSUE TITLE
Condense any unit types larger than 4BR into "4+ Bedroom" filter option

### ISSUE THREAD

**Issue by clairehubel** [philhawksworth/the-united-effort-orginization#76]
@trevorshannon  One of Wei's comments was that there were too many filter options in 'Type of Unit'.

Could we reduce this by eliminating the filter options for 5 bedroom and 6 bedroom, and changing the 4 bedroom filter to '4 or more'......? I doubt that there are that many housing options with 5 or 6 bedrooms, so combining them with 4 bedroom places likely won't be a problem?

LMK your thoughts.

:)

**Comment by trevorshannon** [comment]
Yes, we could certainly do that.  An interesting idea!

**Comment by trevorshannon** [comment]
"Others" has been eliminated as an option.  the "4+ Bedroom" idea is still a good one but isn't implemented yet.

**Comment by clairehubel** [comment]
No worries.....just an improvement for the future, not a priority.

**Comment by clairehubel** [comment]
👍
Claire Hubel
she/her/hers
The United Effort Organization, Inc.
www.theunitedeffort.org <https://www.theunitedeffort.org/>
cell: 650-906-3158
