### ISSUE TITLE
Remove transparency from favicon

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#81]
@philhawksworth As the logo used for the favicon is a bit fine-detailed, perhaps we could get better contrast with varying background colors if we put it inside a white circle, square, or hex.

<img width="215" alt="Screen Shot 2022-05-14 at 2 40 29 PM" src="https://user-images.githubusercontent.com/4656936/168449022-1c83cf36-cfec-42f9-a00d-9ddb02d0a467.png">

**Comment by philhawksworth** [comment]
Agreed.

@clairehubel is supplying a designed favicon which we will use in place of this.

**Comment by philhawksworth** [comment]
New favicons based on this provided image:

![The United Effort favicon](https://user-images.githubusercontent.com/5865/168481408-07743ba5-3de0-4d2e-ad0c-01078e3875fb.png)
