### ISSUE TITLE
Update color of "Print this list" button 

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#84]
There have been comments from a few people that the grey color for the print button makes it look inactive.

It's important to have it be not exactly the same as the "Update Results" button because we want to have the primary action button to be distinct from secondary buttons. However, the grey is probably not the best way to do that.

One way to go would be an outlined button instead of filled in.  This seems to be a generally-accepted best practice.  See https://uxplanet.org/ive-been-doing-buttons-wrong-have-you-2117c0066613

I'll take a look at updating the style.

@clairehubel and @philhawksworth

**Comment by clairehubel** [comment]
@trevorshannon So interesting! So much danger of falling down many a rabbit-hole with this stuff!

Thanks for this great point, and I agree that the outlined button in the same color would be a good solution here. Not critical for the launch, just something for the list.

**Comment by philhawksworth** [comment]
We are all thinking the same way! I had planned to make this same issue suggesting the same approach!

I plan to define some button types to promote consistency across the site:

- Primary (with / without icon)
- Secondary (with / without icon)
- Tertiary (these are styled as links rathe than buttons)
