### ISSUE TITLE
Update DNS records to point to Netlify site for launch

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#89]
Let's make a list of steps to complete in order to execute the switch from our current site hosted by HostGator to our new site hosted on Netlify.

More info on custom domains on Netlify: https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/

- [x] Modify www subdomain CNAME and apex domain A records to have a 10 minute TTL about 24 hours ahead of the switchover
- [x] Add theunutedeffort.org as a custom domain to the site config in Netlify
- [x] Confirm that all other [issues of the 2.0 Relaunch Milestone](https://github.com/philhawksworth/the-united-effort-orginization/milestone/1) are complete (@clairehubel has approved the launch on that basis)
- [x] Point A record and CNAME to Netlify
- [x] Confirm that we are seeing the new site served in good oder on [theunitedeffort.org](http://theunitedeffort.org)
- [x] Provision cert for TLS via Netlify site config
- [x] Set www as primary domain in Netlify config
- [x] Verify DNS propagation with e.g. https://dnschecker.org/
- [x] Inform @clairehubel that we are live
- [x] Close this issue and the [milestone](https://github.com/philhawksworth/the-united-effort-orginization/milestone/1)

**Comment by philhawksworth** [comment]
@clairehubel Can we get a little comment or a 👍 on this issue that you are happy for us to launch as soon as the remaining issues in the [Milestone](https://github.com/philhawksworth/the-united-effort-orginization/milestone/1) or complete as we discussed?

**Comment by trevorshannon** [comment]
@philhawksworth it seems that ALIAS, ANAME, or flattened CNAME are not supported within Plesk.  Maybe they are with direct edits via GoDaddy, but I do not have access to that interface.

<img width="569" alt="Screen Shot 2022-05-15 at 6 11 15 AM" src="https://user-images.githubusercontent.com/4656936/168474611-c0c41949-48fc-4837-82b8-e1e3d612e9ed.png">

We can do the 'fallback' option of editing the A and CNAME www records as described [here](https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/#configure-an-apex-domain) though I don't quite understand the www subdomain as primary stuff described [here](https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/#configure-an-apex-domain).  Is that suggesting we make an A record for www.theunitedeffort.org and remove the exsiting CNAME www record and theunited.org A record?  Or do we just update the existing A record and then twiddle some Netlify setting to make www.theunitedeffort.org the "primary domain"?

**Comment by clairehubel** [comment]
This all sounds great. Thumbs up here! :)

**Comment by philhawksworth** [comment]
@trevorshannon, the latter. "Twiddling in Netlify" :)

The "fallback option" will work fine. It's just that it is less resilient and performant than the ideal option.
This is all relative though, and we're talking about optimisations far in excess of the current configuration on the HostGator server.

Let's go for that second option of adding the A record to point the apex domain top Netlify's load balancers:

A record: `@`  :   `75.2.60.5`

And a CNAME to resolve `www.theunitedeffort.org` to the Netlify site:

CNAME: `www`  :  `ueo.netliy.app`

Later, we could look at making Netlify host the nameserver so that we get some very low level DNS optimisations if we like. It would consolidate a few services into one place. but let's save that for another day.

**Comment by philhawksworth** [comment]
I'm seeing no open issues on the milestone other than this one. I think we are ready to go as per @clairehubel's earlier 👍.

Shall we go for it, @trevorshannon?

**Comment by trevorshannon** [comment]
Nice. I will be able to do it in about 2.5 hours (1pm PDT) if that's what we want.  I had told Wei that I would do it at night PDT but it might be nicer to have you on call just in case.  @clairehubel can make the final timing call.

**Comment by philhawksworth** [comment]
Sure thing. I can't be on call much later than that tonight I'm afraid. 
I'll leave it with you and keep an eye on my email from 1pm PT.

My suspicion is that there will be a very low likelihood of users visiting the site during our cutover.

**Comment by trevorshannon** [comment]
I got word from @clairehubel  that 1pm PDT works.  I'll get started shortly and reach out here if I have questions.  @philhawksworth if you prefer some sort of chat (slack, google chat, etc) just let me know.

**Comment by philhawksworth** [comment]
Awesome! Go for it, @trevorshannon! If you're happy, I'm happy. I'll keep an eye on my email and notifications.

**Comment by philhawksworth** [comment]
Woohoo! http://theunitedeffort.org/ 

(Now that the DNS is propagating, we can get the cert sorted for HTTPS)

**Comment by trevorshannon** [comment]
Yes, it seems the cert is coming soon.  I got a bit confused because I was pretty sure we were going for the "external DNS" option, but I could not add the domain on Netlify without having it come in as "Netlify DNS"

The DNS settings on Plesk are as we discussed (www.theunitedeffort.org CNAME -> ueo.netlify.app and theunitedeffort.org A -> 75.2.60.5

Any other Netlify settings, you should have access to @philhawksworth

**Comment by philhawksworth** [comment]
Cert is done now. HTTPS is working
www is resolving for me too.

**Comment by trevorshannon** [comment]
yes, all looks good so far!  I ran some housing searches and stuff works.

**Comment by trevorshannon** [comment]
🍾 🎉

**Comment by clairehubel** [comment]
Amazing! I just can't thank you both enough for all the time, work, and thoughtfulness you have poured into this project. I'm thrilled with the way it looks and functions, and so excited to move ahead with more projects now we have such a solid foundation.

A million thanks! 🎉🎉🎉🎉🎉🎉🎉

**Comment by clairehubel** [comment]
I think 1pm would be fine since Wei has checked through things a couple of times and we haven’t made any major changes since then.

So, let’s aim for naptime at Trevor’s place! (1pm)

Good idea to have Phil available just in case.

:)

**Comment by clairehubel** [comment]
I am fine with proceeding so we can catch any issues with the move before you go to bed, Phil!

:)
Claire
