### ISSUE TITLE
Minor tweak to the linespacing in the housing search results

### ISSUE THREAD

**Issue by philhawksworth** [philhawksworth/the-united-effort-orginization#92]
As we have added more info to each entry in the Housing DB search results listing, a little visual noise has been introduced.

A small update to the line heights and spacing should address that and make this easier for users to parse

<img width="583" alt="Screenshot 2022-05-15 at 10 15 58" src="https://user-images.githubusercontent.com/5865/168465746-99332295-725e-443f-a3b6-76611610d517.png">

**Comment by trevorshannon** [comment]
We can definitely remove that arrow superscript if it helps.  I was trying to hint that the "property website" was in fact the external property website and not our own webpage with further property details.  But the hint is admittedly subtle and perhaps not necessary.

**Comment by philhawksworth** [comment]
No no, I like it and we don't need to remove it for the sake of this issue. 

We might want to consider how we make it consistent for every link that takes you off of this site thought (since we don't have the convention elsewhere).

For the moment I've update the HTML semantics ever so slightly and modified some of the spacing. It takes up more vertical space to convey the same amount of information, but I think this is worth the increased ease of readability when scanning down the list.

Done.

For reference:


## Before
<img width="647" alt="Screenshot 2022-05-15 at 15 57 52" src="https://user-images.githubusercontent.com/5865/168479524-ac2b997a-dad3-4fdd-82bf-3158ddbba8d0.png">

## After
<img width="647" alt="Screenshot 2022-05-15 at 15 58 01" src="https://user-images.githubusercontent.com/5865/168479552-bb56f53c-f6e2-401b-9b22-4231d569dc6c.png">
