### ISSUE TITLE
Support properties with no associated units

### ISSUE THREAD

**Issue by trevorshannon** [philhawksworth/the-united-effort-orginization#93]
College Terrace in Palo Alto has limited info available online, so we only have basic property metadata and no details on unit types.

This situation can be better supported with some conditional logic, as the rendering is not ideal at the moment.

https://ueo.netlify.app/housing/affordable-housing/1369

<img width="500" alt="Screen Shot 2022-05-15 at 6 45 33 AM" src="https://user-images.githubusercontent.com/4656936/168476098-5811c61d-cbae-44ce-bc9b-dc3b513a43ab.png">

<img width="300" alt="Screen Shot 2022-05-15 at 6 46 09 AM" src="https://user-images.githubusercontent.com/4656936/168476118-3591c653-4801-42f1-8cb6-735ba44841cf.png">

**Comment by philhawksworth** [comment]
Nice one, @trevorshannon. I'm not certain of the use case for listing properties which have no associated units, but its good to track this for the sake of completeness.

**Comment by philhawksworth** [comment]
Added some logic to avoid rendering empty unit type badges or undefined strings.
This should be sufficient for now.
