### ISSUE TITLE
Unusual hierarchy in headings on home page

### ISSUE THREAD

**Issue by philhawksworth** [philhawksworth/the-united-effort-orginization#94]
Do we need to have this section header for "What We Do" @clairehubel ? And if so, should we make it a higher level of heading than the one for "Clients We Serve" beneath it?

Are present it feels like the "What We Do" heading should have some prose under it before another section begins ("Clients We Serve")

<img width="638" alt="Screenshot 2022-05-15 at 16 20 30" src="https://user-images.githubusercontent.com/5865/168480416-f3085bc2-a177-4e2e-b6e6-bbbb630fbd91.png">

**Comment by clairehubel** [comment]
Totally agree. That has been irking me as well. Given the new page structure I think this is superfluous. pls could you remove the What We Do?

**Comment by philhawksworth** [comment]
Donezo!
