### ISSUE TITLE
Remove font-awesome dependency

### ISSUE THREAD

**Issue by philhawksworth** [philhawksworth/the-united-effort-orginization#96]
Since we only use Font Awesome for the question mark tooltip icon, we can replace that with some CSS in order to remove a dependancy which has a performance overhead.

This tag will now render a very similar icon: `<span class="icon_info"></span>`

**Comment by philhawksworth** [comment]
Last Contentful Paint down from 0.625s to 0.4611s (Woohoo!)

**Comment by trevorshannon** [comment]
Actually I was wrong, there is an i icon on the property details page and a question mark icon on the filter page.  Can you make a second icon with an info "I" I'd it's not too difficult?

**Comment by philhawksworth** [comment]
That's no problem

**Comment by philhawksworth** [comment]
Added. We can refine this more over time.
